# Generated by Django 3.2.7 on 2021-09-17 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Make_id', models.CharField(max_length=20)),
                ('Make_name', models.CharField(max_length=100)),
                ('Model_id', models.CharField(max_length=20)),
                ('Model_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Discontinued',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discontinued', models.BooleanField(default=False)),
                ('year', models.CharField(max_length=20)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehicle')),
            ],
        ),
    ]
